### ISSUE TITLE
Arena System

### ISSUE THREAD

**Issue by Serializator** [sgtcaze/ZombieEscape#17]
I saw you have a GameArena object in the main class which represents an arena, your plan was to have arenas, but having a global object destroys the whole idea of arenas?

**Comment by eliblaney** [comment]
I agree, the arenas should be in a different class that we can instantiate so teleporting to random spawns, names, and such will be easier. I might work on a pull request with an Arena class, still deciding how it should be done.

**Comment by Serializator** [comment]
The GameArena is basically the Arena class you're talking about, but because it's instantiated in the main class and is used globally it destroys the idea of arenas. So if you're gonna work with signs you could have a map with the sign location and arena. If someone right clicks on the sign with an arena they join it, if it has no arena assigned you can create one.

**Comment by sgtcaze** [comment]
I mentioned in the videos I wanted to provide support for multiple arenas. This will happen. However, the original zombie escape had only 1 game instance running at a time (this is because the game with only a few players is very slow and dead).

So for the time being it is being setup as a 1 instance game, but later support for multiple arenas will be added. This also aid us in short term testing, because it's easier to work with one variable.

**Comment by eliblaney** [comment]
We should close this issue since it's been resolved.
